[versions]
compose-multiplatform = "1.9.3"
koin = "4.1.0"
kotlin = "2.2.20"
kotlinx-atomicfu = "0.29.0"
tika = "3.2.3"

[libraries]
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin" }
tika = { module = "org.apache.tika:tika-core", version.ref = "tika" }

[plugins]
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinx-atomicfu = { id = "org.jetbrains.kotlinx.atomicfu", version.ref = "kotlinx-atomicfu" }